# Generated by Django 3.0 on 2021-04-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.Categoria'),
            preserve_default=False,
        ),
    ]
