# Generated by Django 3.0 on 2021-04-25 00:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210424_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo_post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerto_post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
