# Generated by Django 3.0 on 2021-04-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comentario',
        ),
    ]
