# Generated by Django 3.0 on 2021-04-25 00:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_remove_comentario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
